<?php

namespace AppBundle\Repository;

/**
 * consulta_de_usuarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class consulta_de_usuarioRepository extends \Doctrine\ORM\EntityRepository
{
}
