<?php

namespace AppBundle\Repository;

/**
 * fotosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class fotosRepository extends \Doctrine\ORM\EntityRepository
{
}
