<?php

namespace AppBundle\Repository;

/**
 * informacion_generalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class informacion_generalRepository extends \Doctrine\ORM\EntityRepository
{
}
