<?php

namespace AppBundle\Repository;

/**
 * reserva_tipo_servicioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class reserva_tipo_servicioRepository extends \Doctrine\ORM\EntityRepository
{
}
