<?php

namespace AppBundle\Repository;

/**
 * ventaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ventaRepository extends \Doctrine\ORM\EntityRepository
{
}
